# Copyright (c) 2023 Sebastian Pipping <sebastian@pipping.org>
# SPDX-License-Identifier: BSD-2-Clause

version: 2
updates:

  - package-ecosystem: "github-actions"
    commit-message:
      include: "scope"
      prefix: "Actions"
    directory: "/"
    labels:
      - "enhancement"
    schedule:
      interval: "weekly"
